name: Test

on:
  workflow_call:

jobs:
  test:
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
        node_version:
          - 'lts/-1'
          - 'lts/*'
        experimental:
          - false
        include:
          - node_version: 'latest'
            experimental: true
            os: ubuntu-latest
            architecture: x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          check-latest: true
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm test
