name: Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  test:
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
        node_version:
          - 18
          - 20
        experimental:
          - false
        include:
          - node_version: 21
            experimental: true
            os: ubuntu-latest
            architecture: x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

